---
title: "Econtwitter"
author: "Jeffrey Naecker"
date: "5/19/2019"
output: html_document
---

```{r setup, include=F, echo = F, message = F}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```


```{r packages}
library(rtweet)
library(ggplot2)
library(dplyr)
library(ggrepel)
library(knitr)
library(kableExtra)

theme_set(theme_minimal())
```

```{r data}
tweets <- search_tweets("#econtwitter", n = 1000, include_rts = FALSE)
```

Let's look at the number of tweets tagged with #econtwitter each day.

```{r}
tweets %>%
  ts_plot() +
  labs(title = "Tweets tagged with #econtwitter per day", x = "Date", y = "Number of tweets")
```

Who are the most prolific tweeters, as measured by number of tweets in the data set?

```{r}
tweets %>%
  count(screen_name) %>%
  arrange(desc(n)) %>%
  head(10) %>%
  kable() %>%
  kable_styling("hover", full_width = F)
```

Which users have the most total likes and most total retweets?

```{r}
users <- 
  tweets %>%
  group_by(screen_name) %>%
  summarize(
    total_likes = sum(favorite_count),
    total_retweets = sum(retweet_count),
    retweet_average  = mean(retweet_count),
    favorite_average = mean(favorite_count),
    n_tweets         = n()
  ) 

users %>%
  select(screen_name, total_likes) %>%
  arrange(desc(total_likes)) %>%
  head(10) %>%
  kable() %>%
  kable_styling("hover", full_width = F)


users %>%
  select(screen_name, total_retweets) %>%
  arrange(desc(total_retweets)) %>%
  head(10) %>%
  kable() %>%
  kable_styling("hover", full_width = F)

```

Let's look at *average* tweet popularity by user:

```{r}
users %>%
  mutate(label = if_else(favorite_average >= 60 | retweet_average >= 15, screen_name, "")) %>%
  ggplot(aes(x = favorite_average, y = retweet_average, label = label)) +
  geom_point() +
  geom_text_repel(point.padding = 0.5) 
```

What are the most popular single tweets, as measured by likes? As measured by retweets?

```{r}
# most liked tweets
tweets %>%
  arrange(desc(favorite_count)) %>%
  select(screen_name, favorite_count, text) %>%
  head(10) %>%
  kable() %>%
  kable_styling("hover", full_width = F)


# most retweeted tweets
tweets %>%
  arrange(desc(retweet_count)) %>%
  select(screen_name, retweet_count, text) %>%
  head(10) %>%
  kable() %>%
  kable_styling("hover", full_width = F)
```



